from oracle2mysql import *

ip = "172.17.8.68"
port = "3306"
user = "cesaralmeciga5850"
password = "U@SXQFNiEeShz66wxgzt"
bbdd = "bbdd_cs_bog_movistar_peru"
sqlEngine = sql_connection(ip, port, user, password, bbdd)
mysql_conn = sqlEngine.connect()



ip = '192.168.1.12'
port = 1521
SID = 'csdb'
user = 'data_cesardiaz'
password = 'NuGO1vhRmeID'

oracle_conn = oracle_connection(ip,port,user,password,SID)

df_oracle = pd.DataFrame()

mysql_query = """SELECT 
            MAX(FECHA_GESTION) as fecha
        FROM
            bbdd_cs_bog_movistar_peru.tb_pentaho_gestion_movistar_peru_b2b;"""

lastdate = repRead(mysql_query, mysql_conn)



mysql_queryDelete = """DELETE FROM `bbdd_cs_bog_movistar_peru`.`tb_pentaho_gestion_movistar_peru_b2b`
WHERE FECHA_GESTION = '""" + str(lastdate) + """';"""

executeQuery(mysql_queryDelete, mysql_conn)


oracle_query = """SELECT DISTINCT 
T.FECHA_GESTION,
HORA_GESTION,
T.IDENTIFICACION,
GESTION,
CASUSISTICA,
CONTACTO,
OBSERVACIONES,
USUARIO,
TELEFONO,
SUBCASUISTICA,
MOTIVO_NO_PAGO,
ENTIDAD_IMPAGO,
SUBMOTIVO_NO_PAGO,
T.NUMERO_CUENTA,
FECHA_PAGO,
MONTO_PROMESA,
FECHA_FIN_GESTION,
HORA_FIN_GESTION,
AMBITO,
FIDELIZACION_BENEFICIO,
NO_ACEPTA_BENEFICIO,
DESCUENTO_FACTURA,
MOTIVO_IMPAGO1,
MOTIVO_IMPAGO2,
OPERADOR,
T.DCO_FISCAL AS NRO_DOC_FISCAL
FROM (
SELECT GESTION.FECHA_GESTION AS FECHA_HORA_GESTION,
TO_CHAR(GESTION.FECHA_GESTION,'YYYY-MM-DD') AS FECHA_GESTION ,
 TO_CHAR(GESTION.FECHA_GESTION,'HH24:MI:SS') AS HORA_GESTION,
 GESTION.IDENTIFICACION,
 GESTION,
 CONSECUENCIA AS CASUSISTICA,
 CONTACTO,
 OBSERVACIONES,
 GESTION.USUARIO,
 TELEFONO,
 MOTIVO_NO_PAGO AS SUBCASUISTICA,
 MOTIVO_NO_PAGO2 AS MOTIVO_NO_PAGO,
 ENTIDAD_IMPAGO,
 NULL AS SUBMOTIVO_NO_PAGO,
 gc.NUMERO_CUENTA,
 FECHA_FIN_GESTION AS FECHA_HORA_FIN_GESTION,
 TO_CHAR(FECHA_FIN_GESTION, 'YYYY-MM-DD') AS FECHA_FIN_GESTION,
 TO_CHAR(FECHA_FIN_GESTION, 'HH24:MI:SS') AS HORA_FIN_GESTION,
 AMBITO,
 FIDELIZACION_BENEFICIO,
 NO_ACEPTA_BENEFICIO,
 NULL AS DESCUENTO_FACTURA,
 MOTIVO_IMPAGO1, 
 MOTIVO_IMPAGO2,
 NULL AS OPERADOR,
 gc1.DCO_FISCAL
FROM MOVISTAR_COBRANZA_PERU_PDTI.GESTION
INNER JOIN MOVISTAR_COBRANZA_PERU_PDTI.GESTION_CUENTA gc 
ON gc.FECHA_GESTION = GESTION.FECHA_GESTION
AND gc.IDENTIFICACION = GESTION.IDENTIFICACION
AND gc.USUARIO = GESTION.USUARIO
INNER JOIN MOVISTAR_COBRANZA_PERU_PDTI.GESTION_CUENTA gc1 
ON 
	gc1.IDENTIFICACION = GESTION.IDENTIFICACION
WHERE TO_CHAR(GESTION.FECHA_GESTION,'YYYY-MM-DD') >= '""" + str(lastdate) + """') T
LEFT JOIN 
MOVISTAR_COBRANZA_PERU_PDTI.PROMESA pr ON pr.IDENTIFICACION  = T.IDENTIFICACION
AND pr.NUMERO_CUENTA = T.NUMERO_CUENTA
AND pr.FECHA_GESTION = T.FECHA_HORA_GESTION
WHERE LENGTH(T.DCO_FISCAL)>0"""

df_oracle = pentahoRead(oracle_query, oracle_conn)


to_sql(df_oracle, "tb_pentaho_gestion_movistar_peru_b2b", mysql_conn, 'append', None, 10000)

mysql_conn.close()